export class Fauna {
    idEspecie?:Number;
    codfor?:string;
    nombreCientifico?:string;
    nombreComun?:string;
    autor?:string;
    sinonimia?:string;
    familia?:string;
    numero_lista?:Number;
    fuente?:string;
    categoria?:string;
    oficial?:string;
    habitoCrecimiento?:string;
    tipouso?:string;
    cites?:string;
    nombrecomercial?:string;
    dmc?:Number;
    idFuenteOficial?:Number;
    fechaActual?:Date;
    amenaza?:string;
    cities?:string;
}